### ISSUE TITLE
Front Facing Camera wrong fps(?)

### ISSUE THREAD

**Issue by Eollie** [teamacid/android_device_samsung_galaxys4gmtd#15] opened 2012-06-18 06:42 UTC
When taking a picture or using video with the front facing camera there is four images instead of just one.

Lolcat from fresh boot and taking a picture. 

http://dl.dropbox.com/u/10373328/1340001498740.log

**Comment by bhundven** [comment] 2012-06-18 07:08
I can confirm this issue.

Question:
Is the camera supposed to be 480x640 (guessing that this depends on orientation... guessing this is portrait, landscape would be 640x480)? Can we confirm this resolution with a stock rom logcat?

I know that FFC is vga , so this could be right and truly a problem with fps (probably a simple overlay change).

FYI: Camera 0 (rfc) is CE147. Camera 1 (ffc) is S5KA3DFX.

**Comment by bhundven** [comment] 2012-06-18 07:11
Also, just to note... this bug is a duplicate of bug#13: https://github.com/teamacid/android_device_samsung_galaxys4gmtd/issues/13

In that case, I am closing this bug and posting relevant data in the original issue.

Thanks for posting!

**Closed as completed by bhundven** 2012-06-18 07:11 UTC
