### ISSUE TITLE
FFC dimensions borked

### ISSUE THREAD

**Issue by maxfierke** [teamacid/android_device_samsung_galaxys4gmtd#13] opened 2012-06-10 19:11 UTC
The front facing camera takes pictures all right but the preview and snapshot dimensions are switched (landscape when they should be portrait). The fix should be pretty easy, but it's probably very tedious to figure out.

Maybe someone with a CCACHE setup can figure it all out because compiling will take 5 minutes.

**Comment by bhundven** [comment] 2012-06-18 07:13
https://github.com/teamacid/android_device_samsung_galaxys4gmtd/issues/15

Please take note of my comments in issue#15 (closed... duplicate of this issue)

**Comment by ghost** [comment] 2012-06-18 07:23
Im not sure you understood what I failed to explain. This issue was briefly discussed in the xda thread. The pictures are not being taken properly like Max states about it looks like the picture is four images stacked on top of each other. In the picture linked you can see four images of my head. I think its similar to this but some very different issues. 

http://db.tt/YkeVq8VZ

**Comment by bhundven** [comment] 2012-06-18 07:47
Rather then looking at this from a "set of issues" POV... I'm looking at this from the "code that changed" POV.

The FFC (s5ka3dfx) came from GB Crespo.

https://github.com/teamacid/android_kernel_galaxys4gmtd/commit/51db45b5264323d395dc2ec14c633894a1503c2d

Looking at the code changes, I'm not sure that I agree with these changes.

As well, the device tree libcamera changes came from ICS:

https://github.com/teamacid/android_device_samsung_galaxys4gmtd/commit/5c0adc2299e638a624794b9a70fde8b2f5dc69a9

The mismatch could cause many issues and I feel they are related.

**Comment by ghost** [comment] 2012-06-18 15:16
Ok I understand what you are saying now Bryan. Would a log from any stock buil work or would we need one from a phone flashed to kj6 stock? I had so many problems getting back on CM7 after a flub Im scared to go back right now. I might be able to get somebody from xda to get a log tho if any bml build would work.

**Comment by bhundven** [comment] 2012-06-19 09:59
airfluip1: Not sure why we changed ffc. That'll be a m4xm4n question, and he is AFK. (on second thought, I think it's because we are now building libcamera from source, whereas previously we were using the proprietary binary.)

Eollie: hehe, I'll go back to bml and check it out.

**Comment by maxfierke** [comment] 2012-07-02 21:38
Fixed in CM9/AOKP as of commit 5d73b831a9ef2f4d8b62f41d3b399f61cdc1cc54 on the device tree (this) and commit teamacid/android_kernel_galaxys4gmtd@8e125726125de01bbde5b623fed8927f968d027f on kernel.

Fixed in CM7 as of commit 7141edb362fdb4e47c7b70970ca8246b12277bd8

**Closed as completed** 2012-07-04 03:42 UTC
Labels: bug, CM7, CM9/AOKP, confirmed
